
-- 
DELETE FROM dim_date_times
WHERE LENGTH(CAST(month AS VARCHAR)) > 2 OR
      LENGTH(CAST(year AS VARCHAR)) > 4 OR
      LENGTH(CAST(day AS VARCHAR)) > 2;
	  
-- 
ALTER TABLE dim_date_times
ALTER COLUMN month TYPE VARCHAR(2),
ALTER COLUMN year TYPE VARCHAR(4),
ALTER COLUMN day TYPE VARCHAR(2),
ALTER COLUMN time_period TYPE VARCHAR(10),
ALTER COLUMN date_uuid TYPE UUID USING date_uuid::UUID;